### ISSUE TITLE
Disable ANSI for tracing-subscriber output?

### ISSUE THREAD

**Issue by jstarks** [d-e-s-o/test-log#20]
The default behavior of tracing-subscriber is to include color control codes in output. It does not try to detect whether the output is a terminal as part of this: https://github.com/tokio-rs/tracing/issues/1160.

For test output this is pretty bad, since it means the color control codes get into logs and end up causing downstream log processing code to complain. Would it be reasonable to disable ANSI output (via [SubscriberBuilder::with_ansi](https://docs.rs/tracing-subscriber/0.2.0/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.with_ansi)) in `expand_tracing_init()`? I'd be happy to send a patch.

**Comment by o1iver** [comment]
Maybe this could also support [NO_COLOR](https://no-color.org/).

**Comment by kingli-crypto** [comment]
I tied to implement this, seems [SubscriberBuilder::with_ansi](https://docs.rs/tracing-subscriber/0.2.0/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.with_ansi) require the `ansi` trait.

Do you think should it be enabled by default? Or guarded by another new trait so we don't break backward compatibility

**Comment by d-e-s-o** [comment]
> I tied to implement this, seems [SubscriberBuilder::with_ansi](https://docs.rs/tracing-subscriber/0.2.0/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.with_ansi) require the `ansi` trait.

Nice!

> Do you think should it be enabled by default?

By default we should keep colors, in my opinion. It's how everything else behaves by default.

I'd say if we follow the `NO_COLOR` "standard" then we should do it according to their playbook. Right now if I set `NO_COLOR=1` I *do* get colors, which is very confusing conceptually and not in line with their suggested behavior. As per their documentation:

```c
	char *no_color = getenv("NO_COLOR");
	bool color = true;

	if (no_color != NULL && no_color[0] != '\0')
		color = false;

	/* do getopt(3) and/or config-file parsing to possibly turn color back on */
```
So according to that we shoul just check for the existence of the env variable. Though I suppose special casing `false` and `0` to re-enable coloring (and disable in all other cases) would be fine, but I don't feel strongly.

**Comment by d-e-s-o** [comment]
Also (and I haven't tested that), as mentioned earlier currently it seems as if `env_logger` honors `RUST_LOG_STYLE`. So I think it would be better to do the same instead of introducing our own variable name.

**Comment by d-e-s-o** [comment]
`NO_COLOR` should now be honored properly (https://github.com/d-e-s-o/test-log/pull/50).
