### ISSUE TITLE
test macro hygiene

### ISSUE THREAD

**Issue by Stargateur** [d-e-s-o/test-log#24]
I have a trait that have a `map` method, it's look the macro use imported item from user code.

```none
error[E0034]: multiple applicable items in scope
   --> network\src\tcp.rs:469:3
    |
469 |   #[test_log::test]
    |   ^^^^^^^^^^^^^^^^^ multiple `map` found
    |
    = note: candidate #1 is defined in an impl of the trait `binator_utils::Utils` for the type `T`
    = note: candidate #2 is defined in an impl of the trait `Iterator` for the type `std::str::Split<'a, P>`
    = note: this error originates in the attribute macro `test_log::test` (in Nightly builds, run with -Z macro-backtrace for more info)
help: disambiguate the associated function for candidate #1
    |
469 |   binator_utils::Utils::map(#[test_log::test], #[test_log::test])
    |
help: disambiguate the associated function for candidate #2
    |
469 |   Iterator::map(#[test_log::test], #[test_log::test])
    |

```

**Comment by d-e-s-o** [comment]
Can you provide a minimal example illustration the issue?

**Comment by Stargateur** [comment]
Yes, sorry.

```toml
test-log = { version = "0.2", features = ["trace"] }
env_logger = "0.9"
tracing = {version = "0.1", default-features = false}
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}
```

```rust
trait Foo: Sized {
    fn map(self) -> Self {
        self
    }
}

impl<T> Foo for T {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test_log::test]
    fn foo() {
        42.map();
    }
}
```

cause https://github.com/d-e-s-o/test-log/blob/3b60bc90e85a1ec73d2caa2684589ccf33cf8d7b/src/lib.rs#L120

I believe https://github.com/d-e-s-o/test-log/issues/15#issuecomment-1141358802 would help on this matter. But unsure, I don't know much about proc macro. https://github.com/rust-lang/rust/issues/54727 is about proc macro hygiene.

**Comment by d-e-s-o** [comment]
Interestingly, it's not even that the proc macro is polluting *your* namespace, it's that you are polluting the proc macro's namespace from what I understand. It's reasonably easy to fix in this case, even in a generic manner.

Happy to be proven wrong, but I am not convinced that https://github.com/d-e-s-o/test-log/issues/15#issuecomment-1141358802 has any bearing on the issue. All it suggests is putting the proc macro logic into a different crate and then importing the macros through this crate. That shouldn't have any impact on method resolution or really much of the compilation process.
