### ISSUE TITLE
Test functions with arguments / `test_generator` support

### ISSUE THREAD

**Issue by tv42** [d-e-s-o/test-log#27]
Hi. I started using the crate https://github.com/frehberg/test-generator to have a separate test instance for each test input file, instead of a for loop. This lets me filter tests being run easily etc.

It works like this:

```rust
use test_generator::test_resources;

#[test_resources("testdata/*.input")]
fn test_foo(path: &str) {
    ...
}
```

However, that has forced me to reimplement tracing setup inside that test, instead of using `test-log`. The wrapping functionality, as in `#[test_log::test(tokio::test)]`, can't handle the fact that the test function now has an argument.

Any thoughts?

**Comment by d-e-s-o** [comment]
We should probably see if we can support that use case. Would you mind giving https://github.com/d-e-s-o/test-log/commit/28610f4874be5f3a9c035816695e3dc8363ccec9 a try?
