### ISSUE TITLE
Change of thread name to "impl"

### ISSUE THREAD

**Issue by Panke** [d-e-s-o/test-log#28]
Thanks for test-log! I am using it together with https://insta.rs/docs/ and insta takes the snapshot name from the thread name a thread runs in. This us usually the name of the test function.

test-log changes the name of the thread to impl which breaks this workflow. I currently circumvent it by naming all snapshots manually, but ofc it would be better if that wouldn't be needed.

**Comment by d-e-s-o** [comment]
I don't believe `test-log` touches thread names. So we'd have to understand based on what these change.

**Comment by tamird** [comment]
I think insta takes the snapshot name from the function name, rather than the test name. Prior to #30, `test-log` generates an inner function called `test_impl`, which could be the cause of this issue.
