### ISSUE TITLE
features should not require users to manually include dependencies

### ISSUE THREAD

**Issue by tamird** [d-e-s-o/test-log#36]
See the [features section of the README](https://github.com/d-e-s-o/test-log#features).

I think the usual pattern for this is:
- create a "runtime" crate with optional dependencies on `log` and `trace` which are reexported.
- add a dependency from `test-log` to "runtime". `trace` and `log` features enable `"runtime"/log` and `"runtime"/trace`, respectively.
- from `test-log`, refer to `log` and `trace` as `"runtime"::log` and `"runtime"::trace`, respectively.

This would produce a nicer user experience.

**Comment by d-e-s-o** [comment]
That sounds good to me. Feel free to open a pull request if you have time to work on it.
