### ISSUE TITLE
Publish new release with `env_logger` changes

### ISSUE THREAD

**Issue by fenollp** [d-e-s-o/test-log#42]
Hi!
Could you cut a release containing https://github.com/d-e-s-o/test-log/commit/39438fcd5029e96455df98883bc5030b751b186b ? Thanks!

**Comment by d-e-s-o** [comment]
Hi, why is that bump so important to you?

**Comment by d-e-s-o** [comment]
Closed via bc1a8c08c869277288a22d623a5e04f468ad621b
